extends Node

signal player_hp_changed(current_hp: int, max_hp: int)
signal player_xp_changed(current_xp: int, xp_to_next: int)
signal player_leveled_up(new_level: int)
signal player_died()
signal player_mana_changed(current_mana: int, max_mana: int)
signal combat_event(message: String)
signal damage_dealt(attacker_name: String, defender_name: String, damage: int, world_position: Vector2, is_crit: bool)
signal item_picked_up(item_name: String)
signal game_message(message: String)
signal enemy_defeated(enemy_name: String)
signal all_enemies_defeated()
signal status_applied(target_name: String, effect_type: int)
signal gold_collected(amount: int)
signal enemy_aggro_changed(in_combat: bool)
